server:
  port: "${SERVER_PORT:8081}"
spring:
  application:
    name: "MsRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "${JWT_KEY_SECRET:c3VwZXJzZWNyZXRrZXlzZWNyZXRrZXlzZWNyZXQxMjM0}"
adapters:
  r2dbc:
    host: "${DATABASE_HOST:localhost}"
    port: "${DATABASE_PORT:5432}"
    database: "${DATABASE_NAME:db-request}"
    schema: "${DATABASE_SCHEMA:public}"
    username: "${DATABASE_USER:gestor}"
    password: "${DATABASE_PASSWORD:123456}"
  restconsumer:
    timeout: 5000
    url: "${BASE_URL_MS_AUTH:http://localhost:8080}"
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
routes:
  paths:
    request: "/api/v1/request"
cors:
  allowed-origins: "*"
adapter:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queues:
      loan-notification-email-queue-url: "${QUEUE_URL_NOTIFICATION_EMAIL:https://sqs.us-east-1.amazonaws.com/794490944018/loan-notification-email-queue}"
      loan-calculate-capacity-queue-url: "${QUEUE_URL_CALCULATE_CAPACITY:https://sqs.us-east-1.amazonaws.com/794490944018/loan-calculate-capacity-queue}"
      loan-report-queue-url: "${QUEUE_URL_REPORT_LOAN:https://sqs.us-east-1.amazonaws.com/794490944018/loan-report-queue}"
  restconsumer:
    email: "${ADMIN_EMAIL}"
    password: "${ADMIN_PASSWORD}"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queues:
      validation-results-queue: "${QUEUE_URL_VALIDATION_RESULTS:https://sqs.us-east-1.amazonaws.com/794490944018/validation-results-queue}"
    queueUrl: "${QUEUE_URL_VALIDATION_RESULTS:https://sqs.us-east-1.amazonaws.com/794490944018/validation-results-queue}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
