-- Table: public.status
-- DROP TABLE IF EXISTS public.status;
CREATE TABLE IF NOT EXISTS public.status
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT status_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.status
    OWNER to gestor;

-- Table: public.type_loan
-- DROP TABLE IF EXISTS public.type_loan;
CREATE TABLE IF NOT EXISTS public.type_loan
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    min_amount numeric(18,2) NOT NULL,
    max_amount numeric(18,2) NOT NULL,
    interest_rate double precision NOT NULL,
    automatic_validation boolean NOT NULL DEFAULT false,
    CONSTRAINT type_loan_pkey PRIMARY KEY (id),
    CONSTRAINT chk_type_loan_amounts CHECK (min_amount >= 0::numeric AND max_amount >= 0::numeric AND max_amount >= min_amount),
    CONSTRAINT chk_type_loan_interest CHECK (interest_rate >= 0::double precision)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.type_loan
    OWNER to gestor;

-- Table: public.request_application
-- DROP TABLE IF EXISTS public.request_application;
CREATE TABLE IF NOT EXISTS public.request_application
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    document_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(18,2) NOT NULL,
    term integer NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    loan_type_id bigint NOT NULL,
    status_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT request_application_pkey PRIMARY KEY (id),
    CONSTRAINT fk_request_application_loan_type FOREIGN KEY (loan_type_id)
        REFERENCES public.type_loan (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_request_application_status FOREIGN KEY (status_id)
        REFERENCES public.status (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT chk_request_application_amount CHECK (amount >= 0::numeric),
    CONSTRAINT chk_request_application_term CHECK (term > 0)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.request_application
    OWNER to gestor;

-- ==============================================
-- CREAR ÍNDICES
-- ==============================================

-- Index: idx_request_application_loan_type_id
CREATE INDEX IF NOT EXISTS idx_request_application_loan_type_id
    ON public.request_application USING btree
    (loan_type_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_request_application_status_id
CREATE INDEX IF NOT EXISTS idx_request_application_status_id
    ON public.request_application USING btree
    (status_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Índices adicionales recomendados
CREATE INDEX IF NOT EXISTS idx_request_application_document_number
    ON public.request_application USING btree
    (document_number ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_request_application_email
    ON public.request_application USING btree
    (email ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_request_application_created_at
    ON public.request_application USING btree
    (created_at DESC NULLS LAST)
    TABLESPACE pg_default;

-- ==============================================
-- POBLAR LAS TABLAS
-- ==============================================

-- Insertar estados
INSERT INTO public.status (id, name, description) VALUES
(1, 'PENDIENTE', 'Solicitud registrada y en validación'),
(2, 'APROBADO', 'Solicitud aprobada'),
(3, 'RECHAZADO', 'Solicitud rechazada'),
(4, 'CANCELADO', 'Solicitud cancelada por el usuario'),
(5, 'EN_PROCESO', 'Solicitud en análisis por parte del área de créditos')
ON CONFLICT DO NOTHING;

-- Insertar tipos de préstamo
INSERT INTO public.type_loan (id, name, min_amount, max_amount, interest_rate, automatic_validation) VALUES
(1, 'Consumo', 500000.00, 50000000.00, 0.0185, true),
(2, 'Vehiculo', 3000000.00, 200000000.00, 0.016, false),
(3, 'Hipotecario', 20000000.00, 1000000000.00, 0.0125, false),
(4, 'Libre Inversión', 1000000.00, 80000000.00, 0.0195, true),
(5, 'Educativo', 500000.00, 60000000.00, 0.014, true)
ON CONFLICT DO NOTHING;

-- Reiniciar las secuencias para que los próximos IDs sean correctos
SELECT setval(pg_get_serial_sequence('public.status', 'id'), 5, true);
SELECT setval(pg_get_serial_sequence('public.type_loan', 'id'), 5, true);
